import { Dealer } from "./types";

export const dealers: Dealer[] = [
  // NEW YORK
  { id: "ny-001", name: "Westside Rifle & Pistol Range", slug: "westside-rifle-pistol-range", categories: ["ranges", "instructors"], state: "new-york", city: "New York City", citySlug: "new-york-city", address: "20 W 20th St, New York, NY 10011", phone: "(212) 929-7287", rating: 4.4, reviewCount: 189, description: "Manhattan's only public indoor shooting range, operating since 1964. Offers 25-yard lanes, firearms rentals, NRA-certified instruction, and New York concealed carry courses.", website: "https://westsidepistolrange.com", featured: true },

  { id: "ny-002", name: "John Jovino Co", slug: "john-jovino-nyc", categories: ["gun-shops", "ffl-dealers"], state: "new-york", city: "New York City", citySlug: "new-york-city", address: "183 Grand St, New York, NY 10013", phone: "(212) 925-4881", rating: 4.3, reviewCount: 145, description: "Long-established firearms dealer in Lower Manhattan. Licensed FFL carrying handguns and accessories, handling New York City purchase authorizations and transfers." },
  { id: "ny-003", name: "Seneca Sporting Range", slug: "seneca-sporting-range-nyc", categories: ["ranges", "instructors"], state: "new-york", city: "New York City", citySlug: "new-york-city", address: "6 Seneca Ave, Ridgewood, NY 11385", phone: "(718) 821-5765", rating: 4.2, reviewCount: 132, description: "Indoor shooting range in Queens offering lane rentals, firearms rentals, and NRA-certified safety courses. Serves the NYC metro area with beginner-friendly programs." },

  // NEW JERSEY
  { id: "nj-001", name: "RTSP (Randolph)", slug: "rtsp-randolph", categories: ["ranges", "gun-shops", "instructors"], state: "new-jersey", city: "Newark", citySlug: "newark", address: "1267 Route 10 East, Randolph, NJ 07869", phone: "(862) 214-3728", rating: 4.7, reviewCount: 321, description: "Indoor shooting range and firearms retailer serving northern New Jersey. Features 25-yard and 100-yard lanes, retail sales, NJ firearms ID card assistance, and a full schedule of training courses.", website: "https://rtsp.com" },

  // CALIFORNIA
  { id: "ca-001", name: "LAX Firing Range", slug: "lax-firing-range", categories: ["ranges", "gun-shops", "instructors"], state: "california", city: "Los Angeles", citySlug: "los-angeles", address: "927 W Manchester Blvd, Inglewood, CA 90301", phone: "(310) 568-1515", rating: 4.3, reviewCount: 276, description: "Indoor shooting range near LAX serving the greater Los Angeles area. Offers lane rentals, firearms sales, California FSC testing, and CCW training courses.", website: "https://laxrange.com" },
  { id: "ca-005", name: "Angeles Shooting Ranges", slug: "angeles-shooting-ranges-la", categories: ["ranges", "instructors"], state: "california", city: "Los Angeles", citySlug: "los-angeles", address: "12651 N Little Tujunga Canyon Rd, Sylmar, CA 91342", phone: "(818) 899-7461", rating: 4.4, reviewCount: 312, description: "Outdoor shooting range in the Angeles National Forest north of Los Angeles. Offers pistol, rifle, and shotgun ranges with distances up to 200 yards. Hosts competitions and provides instruction." },
  { id: "ca-006", name: "Martin B. Retting Inc", slug: "martin-b-retting-la", categories: ["gun-shops", "ffl-dealers"], state: "california", city: "Los Angeles", citySlug: "los-angeles", address: "11029 Washington Blvd, Culver City, CA 90232", phone: "(310) 838-2727", rating: 4.5, reviewCount: 198, description: "Culver City firearms dealer with an inventory of new and used handguns, rifles, and shotguns. Licensed FFL offering DROS transfers, consignment sales, and California-compliant firearms." },
  { id: "ca-007", name: "Discount Gun Mart", slug: "discount-gun-mart-san-diego", categories: ["gun-shops", "ffl-dealers"], state: "california", city: "San Diego", citySlug: "san-diego", address: "3180 Midway Dr, San Diego, CA 92110", phone: "(619) 225-3665", rating: 4.3, reviewCount: 267, description: "San Diego firearms retailer with a large inventory of handguns, rifles, and shotguns at competitive prices. Licensed FFL handling DROS transfers and California-compliant builds." },
  { id: "ca-002", name: "Turners Outdoorsman", slug: "turners-outdoorsman-san-bernardino", categories: ["gun-shops", "ffl-dealers"], state: "california", city: "Riverside", citySlug: "riverside", address: "355 Orange Show Rd, San Bernardino, CA 92408", phone: "(909) 889-1185", rating: 4.2, reviewCount: 198, description: "Large firearms and outdoor retailer in the Inland Empire with a wide selection of handguns, rifles, and shotguns. Licensed FFL dealer handling DROS transfers and California-compliant builds.", website: "https://turners.com" },
  { id: "ca-003", name: "The Gun Range San Diego", slug: "gun-range-san-diego", categories: ["ranges", "instructors"], state: "california", city: "San Diego", citySlug: "san-diego", address: "4610 Alvarado Canyon Rd, San Diego, CA 92120", phone: "(619) 286-0612", rating: 4.5, reviewCount: 234, description: "Indoor shooting facility in San Diego offering pistol and rifle lanes, firearms rentals, CCW courses, and basic firearms safety training.", website: "https://thegunrangesandiego.com" },
  { id: "ca-004", name: "Sacramento Black Rifle", slug: "sacramento-black-rifle", categories: ["gun-shops", "ffl-dealers"], state: "california", city: "Sacramento", citySlug: "sacramento", address: "4620 Northgate Blvd, Sacramento, CA 95834", phone: "(916) 550-8460", rating: 4.6, reviewCount: 187, description: "Sacramento firearms dealer specializing in California-compliant rifles and handguns. Licensed FFL offering transfers, consignment sales, and accessories.", website: "https://sacramentoblackrifle.com" },

  // ILLINOIS
  { id: "il-001", name: "Shore Galleries", slug: "shore-galleries-chicago", categories: ["gun-shops", "ffl-dealers"], state: "illinois", city: "Chicago", citySlug: "chicago", address: "6156 N Cicero Ave, Chicago, IL 60646", phone: "(773) 725-1234", rating: 4.5, reviewCount: 215, description: "North Side Chicago firearms dealer operating since 1950. Carries a full inventory of handguns, rifles, and shotguns. Licensed FFL handling transfers and Illinois FOID card purchases.", website: "https://shoregalleries.com" },
  { id: "il-002", name: "Maxon Shooters Supplies", slug: "maxon-shooters-supplies", categories: ["ranges", "gun-shops", "instructors"], state: "illinois", city: "Chicago", citySlug: "chicago", address: "7533 Woodward Ave, Woodridge, IL 60517", phone: "(630) 985-8388", rating: 4.6, reviewCount: 298, description: "Indoor shooting range and retail store serving the Chicago suburbs. Features 14 lanes, a large firearms inventory, Illinois CCL training, and private instruction.", website: "https://maxonshooting.com", featured: true },

  { id: "il-003", name: "GAT Guns", slug: "gat-guns-chicago", categories: ["ranges", "gun-shops", "ffl-dealers"], state: "illinois", city: "Chicago", citySlug: "chicago", address: "970 Milwaukee Ave, Dundee, IL 60118", phone: "(847) 428-0012", rating: 4.5, reviewCount: 234, description: "Indoor shooting range and firearms superstore serving the Chicago metro area. Features 16 lanes, a large retail floor, Illinois FOID and CCL processing assistance, and FFL transfers.", website: "https://gatguns.com" },
  { id: "il-004", name: "Article II Gun Shop", slug: "article-ii-gun-shop-chicago", categories: ["gun-shops", "ffl-dealers", "instructors"], state: "illinois", city: "Chicago", citySlug: "chicago", address: "6201 Oakton St, Morton Grove, IL 60053", phone: "(847) 966-8000", rating: 4.4, reviewCount: 187, description: "Full-service gun shop and FFL dealer in the north suburbs of Chicago. Carries new and used firearms, handles transfers, and offers Illinois CCL and basic firearms safety courses." },

  // TEXAS
  { id: "tx-001", name: "Central Texas Gun Works", slug: "central-texas-gun-works", categories: ["gun-shops", "ffl-dealers", "ranges"], state: "texas", city: "Austin", citySlug: "austin", address: "1901 S Lamar Blvd, Austin, TX 78704", phone: "(512) 693-3474", rating: 4.7, reviewCount: 312, description: "Full-service gun shop in South Austin offering new and used firearms sales, FFL transfers, and an indoor shooting range. Known for knowledgeable staff and competitive transfer fees.", website: "https://centraltexasgunworks.com", featured: true },
  { id: "tx-002", name: "Adelbridge & Co", slug: "adelbridge-and-co", categories: ["gun-shops", "ffl-dealers"], state: "texas", city: "San Antonio", citySlug: "san-antonio", address: "19070 IH 10 W, San Antonio, TX 78257", phone: "(210) 342-7867", rating: 4.8, reviewCount: 245, description: "San Antonio firearms dealer specializing in premium handguns, sporting rifles, and collectible firearms. Family-owned since 1986 with a large inventory and expert gunsmithing services.", website: "https://adelbridgeandco.com", featured: true },
  { id: "tx-003", name: "The Range at Austin", slug: "the-range-at-austin", categories: ["ranges", "instructors"], state: "texas", city: "Austin", citySlug: "austin", address: "8301 N FM 620, Austin, TX 78726", phone: "(512) 891-4779", rating: 4.6, reviewCount: 198, description: "Indoor shooting facility with 40 lanes at distances up to 25 yards. Offers LTC courses, basic firearm safety classes, and private instruction. Rental firearms available for range use.", website: "https://therangeataustin.com", featured: true },
  { id: "tx-004", name: "Shoot Smart", slug: "shoot-smart-fortworth", categories: ["ranges", "gun-shops", "instructors"], state: "texas", city: "Fort Worth", citySlug: "fort-worth", address: "2440 Ross Ave, Fort Worth, TX 76106", phone: "(817) 624-8400", rating: 4.5, reviewCount: 176, description: "Indoor range and retail store in Fort Worth with 30 shooting lanes, a full firearms inventory, and a comprehensive course schedule including women-only classes and advanced defensive shooting.", website: "https://shootsmart.com" },
  { id: "tx-007", name: "Nagel's Gun Shop", slug: "nagels-gun-shop-san-antonio", categories: ["gun-shops", "ffl-dealers", "instructors"], state: "texas", city: "San Antonio", citySlug: "san-antonio", address: "625 Bitters Rd, San Antonio, TX 78216", phone: "(210) 342-5420", rating: 4.6, reviewCount: 213, description: "San Antonio firearms dealer carrying new and used handguns, rifles, and shotguns. Offers FFL transfers, gunsmithing, and LTC training courses.", website: "https://nagels.com" },
  { id: "tx-008", name: "Eagle Peak Shooting Range", slug: "eagle-peak-fort-worth", categories: ["ranges", "instructors"], state: "texas", city: "Fort Worth", citySlug: "fort-worth", address: "3780 Benbrook Hwy, Fort Worth, TX 76116", phone: "(817) 244-4867", rating: 4.4, reviewCount: 165, description: "Indoor shooting range in southwest Fort Worth with 25-yard lanes, firearms rentals, LTC courses, and private instruction for beginners through advanced shooters." },
  { id: "tx-009", name: "Shiloh Shooting Range", slug: "shiloh-shooting-houston", categories: ["ranges", "gun-shops"], state: "texas", city: "Houston", citySlug: "houston", address: "11180 Gulf Fwy, Houston, TX 77034", phone: "(713) 943-1848", rating: 4.5, reviewCount: 198, description: "Indoor shooting range and gun shop in southeast Houston. Features pistol and rifle lanes, a retail firearms inventory, and ammunition sales." },
  { id: "tx-010", name: "DFW Shooting Sports", slug: "dfw-shooting-sports-dallas", categories: ["ranges", "gun-shops", "instructors"], state: "texas", city: "Dallas", citySlug: "dallas", address: "1952 Royal Ln, Dallas, TX 75229", phone: "(972) 243-5151", rating: 4.6, reviewCount: 245, description: "Indoor shooting range and firearms retailer in north Dallas. Features 25-yard lanes, a full retail store, LTC courses, and a variety of training programs for all skill levels." },
  { id: "tx-005", name: "Athena Gun Club", slug: "athena-gun-club-houston", categories: ["ranges", "gun-shops", "instructors"], state: "texas", city: "Houston", citySlug: "houston", address: "14713 Westheimer Rd, Houston, TX 77077", phone: "(281) 293-0050", rating: 4.7, reviewCount: 264, description: "Upscale indoor shooting range and retail store in west Houston. Features climate-controlled lanes, a full firearms inventory, LTC courses, and private instruction for all skill levels.", website: "https://athenagunclub.com", featured: true },
  { id: "tx-006", name: "Elm Fork Shooting Sports", slug: "elm-fork-shooting-dallas", categories: ["ranges", "instructors"], state: "texas", city: "Dallas", citySlug: "dallas", address: "10751 Luna Rd, Dallas, TX 75220", phone: "(972) 556-0103", rating: 4.6, reviewCount: 312, description: "Outdoor shooting sports facility in Dallas offering trap, skeet, sporting clays, and rifle ranges. Hosts competitions and provides instruction for shotgun sports and long-range shooting.", website: "https://elmfork.com" },

  { id: "tx-011", name: "Top Gun Range", slug: "top-gun-range-houston", categories: ["ranges", "instructors"], state: "texas", city: "Houston", citySlug: "houston", address: "2011 S Dairy Ashford Rd, Houston, TX 77077", phone: "(281) 556-8806", rating: 4.5, reviewCount: 176, description: "Indoor shooting range in west Houston offering pistol and rifle lanes, firearms rentals, and a full schedule of LTC and defensive shooting courses." },

  // VIRGINIA
  { id: "va-001", name: "Silver Eagle Group", slug: "silver-eagle-group-arlington", categories: ["ranges", "gun-shops", "instructors"], state: "virginia", city: "Arlington", citySlug: "arlington", address: "14037 Willard Rd, Chantilly, VA 20151", phone: "(703) 817-3700", rating: 4.6, reviewCount: 243, description: "Indoor shooting range and firearms retailer serving Northern Virginia. Features 25-yard lanes, retail sales, Virginia CHP classes, and NRA-certified training programs.", website: "https://silvereaglegroup.com", featured: true },

  // PENNSYLVANIA
  { id: "pa-001", name: "Philadelphia Training Academy", slug: "philadelphia-training-academy", categories: ["ranges", "instructors"], state: "pennsylvania", city: "Philadelphia", citySlug: "philadelphia", address: "308 N 63rd St, Philadelphia, PA 19139", phone: "(215) 922-4867", rating: 4.4, reviewCount: 156, description: "Indoor shooting range and training center in Philadelphia offering lane rentals, LTCF preparation courses, basic pistol safety, and private instruction.", website: "https://philadelphiatrainingacademy.com" },
  { id: "pa-002", name: "Anthony Arms", slug: "anthony-arms-pittsburgh", categories: ["gun-shops", "ffl-dealers", "ranges"], state: "pennsylvania", city: "Pittsburgh", citySlug: "pittsburgh", address: "359 Freeport Rd, Pittsburgh, PA 15238", phone: "(412) 828-3323", rating: 4.6, reviewCount: 198, description: "Full-service gun shop and indoor range in the Pittsburgh area. Carries a wide selection of new and used firearms, handles FFL transfers, and operates a 12-lane indoor range.", website: "https://anthonyarms.com", featured: true },

  { id: "va-002", name: "Clark Brothers Guns", slug: "clark-brothers-arlington", categories: ["gun-shops", "ffl-dealers"], state: "virginia", city: "Arlington", citySlug: "arlington", address: "225 N Washington St, Warrenton, VA 20186", phone: "(540) 347-5570", rating: 4.5, reviewCount: 187, description: "Firearms dealer serving Northern Virginia with a large inventory of new and used handguns, rifles, and shotguns. Licensed FFL offering transfers and Virginia CHP preparation." },
  { id: "pa-003", name: "Targetmaster", slug: "targetmaster-philadelphia", categories: ["ranges", "gun-shops", "instructors"], state: "pennsylvania", city: "Philadelphia", citySlug: "philadelphia", address: "127 E County Line Rd, Chalfont, PA 18914", phone: "(215) 822-8680", rating: 4.5, reviewCount: 213, description: "Indoor shooting range and firearms retailer serving the Philadelphia suburbs. Features 50-foot lanes, retail sales, LTCF courses, and NRA-certified instruction.", website: "https://targetmaster.com" },
  { id: "pa-004", name: "Corliss Arms", slug: "corliss-arms-pittsburgh", categories: ["gun-shops", "ffl-dealers"], state: "pennsylvania", city: "Pittsburgh", citySlug: "pittsburgh", address: "501 Station St, Pittsburgh, PA 15206", phone: "(412) 362-7436", rating: 4.4, reviewCount: 156, description: "Pittsburgh firearms dealer carrying handguns, rifles, shotguns, and accessories. Licensed FFL offering transfers, consignment, and a knowledgeable staff focused on customer service." },

  // FLORIDA
  { id: "fl-001", name: "Shoot Straight", slug: "shoot-straight-tampa", categories: ["ranges", "gun-shops", "instructors"], state: "florida", city: "Tampa", citySlug: "tampa", address: "3951 W Hillsborough Ave, Tampa, FL 33614", phone: "(813) 879-7867", rating: 4.6, reviewCount: 289, description: "One of Florida's largest gun stores and indoor ranges with multiple Tampa Bay area locations. Extensive inventory of handguns, rifles, and shotguns with competitive pricing and knowledgeable staff.", website: "https://shootstraight.com", featured: true },
  { id: "fl-002", name: "The Gun Range Miami", slug: "gun-range-miami", categories: ["ranges", "instructors"], state: "florida", city: "Miami", citySlug: "miami", address: "1950 NW 7th Ave, Miami, FL 33136", phone: "(305) 573-4867", rating: 4.5, reviewCount: 167, description: "Indoor shooting facility in Miami offering 25-yard lanes, firearms rentals, concealed carry courses, and private instruction in English and Spanish.", website: "https://thegunrangemiami.com" },
  { id: "fl-003", name: "Nexus Shooting", slug: "nexus-shooting-fort-lauderdale", categories: ["ranges", "gun-shops", "instructors"], state: "florida", city: "Fort Lauderdale", citySlug: "fort-lauderdale", address: "1401 SW 1st Ave, Fort Lauderdale, FL 33315", phone: "(954) 337-2894", rating: 4.7, reviewCount: 287, description: "Indoor shooting range and firearms retailer in Fort Lauderdale with 25-yard lanes, a full retail store, and a comprehensive training program including Florida CWL courses.", website: "https://nexusshooting.com" },
  { id: "fl-004", name: "Shoot Center Orlando", slug: "shoot-center-orlando", categories: ["ranges", "gun-shops", "instructors"], state: "florida", city: "Orlando", citySlug: "orlando", address: "5679 S Orange Blossom Trl, Orlando, FL 32839", phone: "(407) 855-7867", rating: 4.5, reviewCount: 213, description: "Indoor shooting range and retail store in Orlando. Features pistol and rifle lanes, a large firearms inventory, Florida CWL classes, and beginner-friendly instruction.", website: "https://shootcenter.com" },

  { id: "fl-005", name: "Lock & Load Miami", slug: "lock-load-miami", categories: ["ranges", "gun-shops"], state: "florida", city: "Miami", citySlug: "miami", address: "2850 NW 46th St, Miami, FL 33142", phone: "(305) 633-8544", rating: 4.4, reviewCount: 198, description: "Indoor shooting range and gun shop in Miami offering lane rentals, firearms sales, and an extensive rental collection including full-auto firearms for range use." },
  { id: "fl-006", name: "East Orange Shooting Sports", slug: "east-orange-shooting-orlando", categories: ["ranges", "gun-shops", "instructors"], state: "florida", city: "Orlando", citySlug: "orlando", address: "2475 E Young Pine Rd, Kissimmee, FL 34744", phone: "(407) 932-7675", rating: 4.6, reviewCount: 245, description: "Indoor and outdoor shooting facility near Orlando with pistol, rifle, and shotgun ranges. Features a retail store, Florida CWL courses, and private instruction." },
  { id: "fl-007", name: "Shoot Straight Fort Lauderdale", slug: "shoot-straight-fort-lauderdale", categories: ["ranges", "gun-shops", "instructors"], state: "florida", city: "Fort Lauderdale", citySlug: "fort-lauderdale", address: "2950 S State Rd 7, Fort Lauderdale, FL 33312", phone: "(954) 986-7867", rating: 4.5, reviewCount: 198, description: "Full-service gun store and indoor range in Fort Lauderdale. Part of the Shoot Straight chain with a large inventory, competitive pricing, and CWL training courses." },

  // GEORGIA
  { id: "ga-001", name: "Stoddard's Range and Guns", slug: "stoddards-atlanta", categories: ["ranges", "gun-shops", "instructors"], state: "georgia", city: "Atlanta", citySlug: "atlanta", address: "4655 Jimmy Carter Blvd, Norcross, GA 30093", phone: "(770) 263-8550", rating: 4.6, reviewCount: 212, description: "Full-service firearms facility in the Atlanta metro offering an indoor range, retail sales, gunsmithing, and courses including Georgia Weapons Carry License classes.", website: "https://stoddards.com", featured: true },
  { id: "ga-002", name: "Quickshot Shooting Range", slug: "quickshot-atlanta", categories: ["ranges", "instructors"], state: "georgia", city: "Atlanta", citySlug: "atlanta", address: "1789 NE Expy NE, Atlanta, GA 30329", phone: "(404) 315-7867", rating: 4.5, reviewCount: 178, description: "Indoor shooting range in northeast Atlanta offering lane rentals, firearms rentals, and training courses. Features 50-foot lanes and a variety of rental handguns and rifles." },

  { id: "ga-003", name: "Adventure Outdoors", slug: "adventure-outdoors-atlanta", categories: ["gun-shops", "ffl-dealers"], state: "georgia", city: "Atlanta", citySlug: "atlanta", address: "4602 S Cobb Dr SE, Smyrna, GA 30080", phone: "(770) 432-9686", rating: 4.5, reviewCount: 287, description: "Large firearms and outdoor retailer in the Atlanta metro area. Carries an extensive inventory of handguns, rifles, and shotguns with competitive pricing and FFL transfer services." },

  // MASSACHUSETTS
  { id: "ma-001", name: "Mass Firearms School", slug: "mass-firearms-school-boston", categories: ["ranges", "instructors"], state: "massachusetts", city: "Boston", citySlug: "boston", address: "70 Fottler Rd, Holliston, MA 01746", phone: "(508) 429-1320", rating: 4.5, reviewCount: 189, description: "Indoor shooting range and training center serving the Boston metro area. Offers Massachusetts LTC classes, basic firearms safety required for licensing, and NRA-certified instruction.", website: "https://massfirearmsschool.com", featured: true },

  { id: "ma-002", name: "Four Seasons Firearms", slug: "four-seasons-firearms-boston", categories: ["gun-shops", "ffl-dealers"], state: "massachusetts", city: "Boston", citySlug: "boston", address: "911 Boylston St, Brookline, MA 02446", phone: "(617) 566-5500", rating: 4.4, reviewCount: 165, description: "Brookline firearms dealer serving the Boston metro area. Carries handguns, rifles, and shotguns. Assists with Massachusetts LTC applications and FID card processing." },

  // ARIZONA
  { id: "az-001", name: "Scottsdale Gun Club", slug: "scottsdale-gun-club", categories: ["ranges", "gun-shops", "instructors"], state: "arizona", city: "Scottsdale", citySlug: "scottsdale", address: "14860 N Northsight Blvd, Scottsdale, AZ 85260", phone: "(480) 348-1111", rating: 4.8, reviewCount: 356, description: "Premier indoor shooting range and retail store in Scottsdale with climate-controlled lanes, a large firearms inventory, and expert instruction programs from basic safety to advanced tactical.", website: "https://scottsdalegc.com", featured: true },
  { id: "az-002", name: "Caswells Shooting Range", slug: "caswells-mesa", categories: ["ranges", "gun-shops"], state: "arizona", city: "Mesa", citySlug: "mesa", address: "2424 N Mesa Dr, Mesa, AZ 85201", phone: "(480) 461-0411", rating: 4.5, reviewCount: 198, description: "Family-owned indoor shooting range and gun shop in Mesa serving the East Valley. Offers lane rentals, firearms sales, and a selection of rental guns for range use.", website: "https://caswells.com" },
  { id: "az-003", name: "C2 Tactical", slug: "c2-tactical-phoenix", categories: ["ranges", "gun-shops", "instructors"], state: "arizona", city: "Phoenix", citySlug: "phoenix", address: "8475 S Emerald Dr, Tempe, AZ 85284", phone: "(480) 588-8802", rating: 4.7, reviewCount: 315, description: "Indoor shooting range and firearms retailer in the Phoenix metro with 40 lanes, a large retail space, and a full training schedule from beginner to advanced tactical courses.", website: "https://c2tactical.com", featured: true },

  { id: "az-004", name: "Bear Arms Firearms", slug: "bear-arms-phoenix", categories: ["gun-shops", "ffl-dealers"], state: "arizona", city: "Phoenix", citySlug: "phoenix", address: "3454 E Thomas Rd, Phoenix, AZ 85018", phone: "(602) 957-3300", rating: 4.4, reviewCount: 178, description: "Phoenix firearms dealer carrying handguns, rifles, shotguns, and accessories. Licensed FFL offering transfers, trade-ins, and consignment sales." },

  // MICHIGAN
  { id: "mi-001", name: "Top Gun Shooting Sports", slug: "top-gun-shooting-detroit", categories: ["ranges", "gun-shops", "instructors"], state: "michigan", city: "Detroit", citySlug: "detroit", address: "37300 Van Dyke Ave, Sterling Heights, MI 48312", phone: "(586) 276-4867", rating: 4.6, reviewCount: 223, description: "Indoor shooting range and firearms retailer in metro Detroit. Features 25-yard lanes, retail sales, Michigan CPL courses, and a variety of training programs.", website: "https://topgunmi.com", featured: true },

  // WASHINGTON
  { id: "wa-001", name: "Wade's Eastside Guns", slug: "wades-eastside-guns-seattle", categories: ["gun-shops", "ffl-dealers", "ranges"], state: "washington", city: "Seattle", citySlug: "seattle", address: "13570 Bel-Red Rd, Bellevue, WA 98005", phone: "(425) 649-7887", rating: 4.4, reviewCount: 198, description: "Gun shop and indoor range serving the Seattle metro area. Offers firearms sales, FFL transfers, lane rentals, and Washington CPL courses.", website: "https://wadesguns.com" },

  // MINNESOTA
  { id: "mn-001", name: "Bill's Gun Shop & Range", slug: "bills-gun-shop-minneapolis", categories: ["gun-shops", "ranges", "instructors"], state: "minnesota", city: "Minneapolis", citySlug: "minneapolis", address: "4080 W Broadway Ave, Robbinsdale, MN 55422", phone: "(763) 533-9594", rating: 4.5, reviewCount: 267, description: "Full-service gun shop and indoor range in the Minneapolis metro area. Carries an extensive firearms inventory, handles FFL transfers, and offers Minnesota permit-to-carry courses.", website: "https://billsgs.com", featured: true },

  // COLORADO
  { id: "co-001", name: "Bristlecone Shooting", slug: "bristlecone-shooting", categories: ["ranges", "gun-shops", "instructors"], state: "colorado", city: "Lakewood", citySlug: "lakewood", address: "12105 W Cedar Dr, Lakewood, CO 80228", phone: "(303) 985-0989", rating: 4.7, reviewCount: 234, description: "Modern indoor shooting facility west of Denver with 20 lanes, retail firearms sales, gunsmithing, and a full curriculum of courses from beginner to advanced. Known for a welcoming atmosphere for new shooters.", website: "https://bristleconeshooting.com", featured: true },
  { id: "co-002", name: "Centennial Gun Club", slug: "centennial-gun-club-denver", categories: ["ranges", "gun-shops", "instructors"], state: "colorado", city: "Denver", citySlug: "denver", address: "11800 E Peakview Ave, Centennial, CO 80111", phone: "(303) 789-2582", rating: 4.6, reviewCount: 256, description: "Indoor shooting range and firearms retailer serving the Denver metro area. Features 25-yard lanes, a full retail store, Colorado CHP classes, and private instruction.", website: "https://centennialgunclub.com" },

  // MISSOURI
  { id: "mo-001", name: "The Shooting Institute", slug: "shooting-institute-stlouis", categories: ["ranges", "instructors"], state: "missouri", city: "Saint Louis", citySlug: "saint-louis", address: "12150 Lackland Rd, St. Louis, MO 63146", phone: "(314) 432-4867", rating: 4.5, reviewCount: 187, description: "Indoor shooting range and training center in west St. Louis County. Offers lane rentals, Missouri CCW courses, and a variety of firearms training programs.", website: "https://theshootinginstitute.com" },
  { id: "mo-002", name: "Frontier Justice", slug: "frontier-justice-kc", categories: ["ranges", "gun-shops", "instructors"], state: "missouri", city: "Kansas City", citySlug: "kansas-city", address: "1370 NW Chipman Rd, Lee's Summit, MO 64081", phone: "(816) 287-9555", rating: 4.8, reviewCount: 342, description: "Premium indoor shooting range and firearms retailer in the Kansas City metro area. Features 56 shooting lanes, a large retail floor, and a comprehensive training program.", website: "https://frontierjustice.com", featured: true },

  // MARYLAND
  { id: "md-001", name: "Atlantic Guns", slug: "atlantic-guns-baltimore", categories: ["gun-shops", "ffl-dealers"], state: "maryland", city: "Baltimore", citySlug: "baltimore", address: "6920 Riverdale Rd, Riverdale Park, MD 20737", phone: "(301) 459-3358", rating: 4.4, reviewCount: 176, description: "Established firearms dealer serving the Baltimore–Washington corridor. Carries handguns, rifles, and shotguns with Maryland HQL assistance and FFL transfer services.", website: "https://atlanticguns.com" },

  // NORTH CAROLINA
  { id: "nc-001", name: "ProShots Indoor Range", slug: "proshots-charlotte", categories: ["ranges", "gun-shops", "instructors"], state: "north-carolina", city: "Charlotte", citySlug: "charlotte", address: "7008 South Blvd, Charlotte, NC 28217", phone: "(980) 237-4867", rating: 4.6, reviewCount: 213, description: "Indoor shooting range and firearms retailer in south Charlotte. Features 25-yard lanes, retail sales, North Carolina CHP courses, and beginner-friendly instruction.", website: "https://proshotsrange.com", featured: true },

  // OREGON
  { id: "or-001", name: "The Gun Room", slug: "gun-room-portland", categories: ["gun-shops", "ffl-dealers"], state: "oregon", city: "Portland", citySlug: "portland", address: "8621 SE Foster Rd, Portland, OR 97266", phone: "(503) 775-2828", rating: 4.5, reviewCount: 165, description: "Portland gun shop carrying a selection of new and used firearms. Licensed FFL handling transfers, with a focus on handguns, sporting rifles, and accessories.", website: "https://thegunroompdx.com" },

  { id: "or-002", name: "Tigard Pawn & Gun", slug: "tigard-pawn-gun-portland", categories: ["gun-shops", "ffl-dealers"], state: "oregon", city: "Portland", citySlug: "portland", address: "12024 SW Main St, Tigard, OR 97223", phone: "(503) 620-1250", rating: 4.3, reviewCount: 143, description: "Portland-area firearms dealer carrying new and used handguns, rifles, and shotguns. Licensed FFL offering transfers and a selection of ammunition and accessories." },

  // NEVADA
  { id: "nv-001", name: "The Range 702", slug: "range-702-las-vegas", categories: ["ranges", "gun-shops", "instructors"], state: "nevada", city: "Las Vegas", citySlug: "las-vegas", address: "5999 Dean Martin Dr, Las Vegas, NV 89118", phone: "(702) 802-1700", rating: 4.7, reviewCount: 456, description: "Indoor shooting range and firearms retailer in Las Vegas. Features 25-yard lanes, an extensive rental collection, Nevada CCW courses, and beginner packages for first-time shooters.", website: "https://therange702.com", featured: true },

  { id: "nv-002", name: "Discount Firearms & Ammo", slug: "discount-firearms-las-vegas", categories: ["gun-shops", "ffl-dealers"], state: "nevada", city: "Las Vegas", citySlug: "las-vegas", address: "3427 W Craig Rd, North Las Vegas, NV 89032", phone: "(702) 646-4867", rating: 4.5, reviewCount: 287, description: "Las Vegas firearms retailer with a large inventory of handguns, rifles, and shotguns at competitive prices. Licensed FFL handling transfers, with a focus on ammunition availability." },
  { id: "nv-003", name: "Clark County Shooting Complex", slug: "clark-county-shooting-complex", categories: ["ranges", "instructors"], state: "nevada", city: "Las Vegas", citySlug: "las-vegas", address: "11357 N Decatur Blvd, Las Vegas, NV 89131", phone: "(702) 455-2000", rating: 4.6, reviewCount: 234, description: "Public outdoor shooting facility operated by Clark County. Offers pistol, rifle, and shotgun ranges with distances up to 200 yards. Hosts competitions and provides basic instruction." },

  // INDIANA
  { id: "in-001", name: "Indy Arms Company", slug: "indy-arms-company", categories: ["ranges", "gun-shops", "instructors"], state: "indiana", city: "Indianapolis", citySlug: "indianapolis", address: "6950 Woodland Dr, Indianapolis, IN 46278", phone: "(317) 377-4867", rating: 4.6, reviewCount: 198, description: "Indoor shooting range and firearms retailer in Indianapolis. Features 24 lanes, retail sales, Indiana handgun license training, and NRA-certified instruction.", website: "https://indyarmsco.com", featured: true },

  { id: "in-002", name: "Beech Grove Firearms", slug: "beech-grove-firearms-indy", categories: ["gun-shops", "ffl-dealers"], state: "indiana", city: "Indianapolis", citySlug: "indianapolis", address: "601 Main St, Beech Grove, IN 46107", phone: "(317) 788-4867", rating: 4.5, reviewCount: 176, description: "Indianapolis-area firearms dealer specializing in handguns, sporting rifles, and accessories. Licensed FFL offering transfers and trade-ins with personalized service." },

  // TENNESSEE
  { id: "tn-001", name: "Royal Range USA", slug: "royal-range-nashville", categories: ["ranges", "gun-shops", "instructors"], state: "tennessee", city: "Nashville", citySlug: "nashville", address: "7741 Hwy 70 S, Nashville, TN 37221", phone: "(615) 646-9333", rating: 4.7, reviewCount: 287, description: "Indoor shooting range and firearms retailer in Nashville. Features 26 lanes, a full retail store, Tennessee Enhanced Handgun Carry Permit courses, and a wide range of training programs.", website: "https://royalrangeusa.com", featured: true },

  { id: "tn-002", name: "Nashville Armory", slug: "nashville-armory", categories: ["ranges", "gun-shops", "instructors"], state: "tennessee", city: "Nashville", citySlug: "nashville", address: "4290 Kenilwood Dr, Nashville, TN 37204", phone: "(615) 730-4867", rating: 4.6, reviewCount: 213, description: "Indoor shooting range and firearms retailer in Nashville. Features lane rentals, retail sales, Tennessee Enhanced Handgun Carry Permit courses, and private instruction." },

  // OHIO
  { id: "oh-001", name: "Vance Outdoors", slug: "vance-outdoors-columbus", categories: ["gun-shops", "ffl-dealers"], state: "ohio", city: "Columbus", citySlug: "columbus", address: "1774 W Morse Rd, Columbus, OH 43229", phone: "(614) 888-4867", rating: 4.6, reviewCount: 287, description: "Large firearms retailer in Columbus carrying an extensive selection of handguns, rifles, shotguns, and ammunition. Licensed FFL dealer offering transfers, layaway, and trade-ins.", website: "https://vanceoutdoors.com", featured: true },
  { id: "oh-002", name: "Point Blank Range & Gun Shop", slug: "point-blank-range-cincinnati", categories: ["ranges", "gun-shops", "instructors"], state: "ohio", city: "Cincinnati", citySlug: "cincinnati", address: "4600 Lake Forest Dr, Cincinnati, OH 45242", phone: "(513) 469-8000", rating: 4.7, reviewCount: 203, description: "Indoor shooting range and retail store in Cincinnati with 25-yard lanes, a full firearms inventory, and a variety of training courses including Ohio CCW certification and basic pistol safety.", website: "https://pointblankrange.com" },
  { id: "oh-003", name: "Stonewall Firearms", slug: "stonewall-firearms-cleveland", categories: ["gun-shops", "ffl-dealers", "instructors"], state: "ohio", city: "Cleveland", citySlug: "cleveland", address: "6874 Pearl Rd, Middleburg Heights, OH 44130", phone: "(440) 243-4867", rating: 4.5, reviewCount: 164, description: "Family-owned gun shop near Cleveland offering new and used firearms sales, FFL transfers, and Ohio concealed carry classes. Carries handguns, long guns, and accessories from major manufacturers.", website: "https://stonewallfirearms.com" },
];

export const getDealersByState = (stateSlug: string): Dealer[] =>
  dealers.filter((d) => d.state === stateSlug);

export const getDealersByCategory = (catSlug: string): Dealer[] =>
  dealers.filter((d) => d.categories.includes(catSlug));

export const getDealerBySlug = (slug: string): Dealer | undefined =>
  dealers.find((d) => d.slug === slug);

export const getDealersByCity = (stateSlug: string, citySlug: string): Dealer[] =>
  dealers.filter((d) => d.state === stateSlug && d.citySlug === citySlug);

export const getDealerByStateAndSlug = (stateSlug: string, dealerSlug: string): Dealer | undefined =>
  dealers.find((d) => d.state === stateSlug && d.slug === dealerSlug);
