import { State } from "./types";

export const states: State[] = [
  { name: "Texas", slug: "texas", abbr: "TX", permitRequired: false, constitutionalCarry: true, description: "Texas adopted constitutional carry in September 2021 under HB 1927, allowing residents 21 and older to carry handguns without a permit. The License to Carry (LTC) remains available and is recommended for reciprocity with other states." },
  { name: "Florida", slug: "florida", abbr: "FL", permitRequired: false, constitutionalCarry: true, description: "Florida enacted permitless concealed carry in July 2023 under SB 150. Open carry remains prohibited in most circumstances. The concealed weapon license (CWL) is still available for reciprocity purposes." },
  { name: "California", slug: "california", abbr: "CA", permitRequired: true, constitutionalCarry: false, description: "California requires a Concealed Carry Weapon (CCW) permit issued by the county sheriff or local police chief. The state has some of the most restrictive firearms laws in the nation, including an assault weapons ban and mandatory waiting periods." },
  { name: "New York", slug: "new-york", abbr: "NY", permitRequired: true, constitutionalCarry: false, description: "New York requires a license to possess and carry handguns, administered at the county level. Following the Bruen decision, the state enacted the Concealed Carry Improvement Act with new requirements for permit applicants." },
  { name: "Arizona", slug: "arizona", abbr: "AZ", permitRequired: false, constitutionalCarry: true, description: "Arizona was one of the first states to adopt constitutional carry in 2010. Any person 21 or older who can legally possess a firearm may carry concealed without a permit. The state issues a Concealed Weapons Permit for reciprocity." },
  { name: "Georgia", slug: "georgia", abbr: "GA", permitRequired: false, constitutionalCarry: true, description: "Georgia enacted constitutional carry in April 2022 under SB 319. Georgia residents 21 and older (or 18 and older for military) may carry handguns without a license. The Georgia Weapons Carry License remains available." },
  { name: "Ohio", slug: "ohio", abbr: "OH", permitRequired: false, constitutionalCarry: true, description: "Ohio adopted constitutional carry in June 2022 under SB 215. Adults 21 and older who are legally eligible to possess firearms may carry concealed without a permit. The Concealed Handgun License (CHL) is still available." },
  { name: "Colorado", slug: "colorado", abbr: "CO", permitRequired: true, constitutionalCarry: false, description: "Colorado requires a Concealed Handgun Permit (CHP) for concealed carry, issued by the county sheriff. The state has enacted several gun safety measures in recent years including a red flag law and expanded background check requirements." },
  { name: "Pennsylvania", slug: "pennsylvania", abbr: "PA", permitRequired: true, constitutionalCarry: false, description: "Pennsylvania requires a License to Carry Firearms (LTCF) for concealed carry, issued by the county sheriff. Open carry is legal without a permit in most of the state, except in Philadelphia where a LTCF is required." },
  { name: "Michigan", slug: "michigan", abbr: "MI", permitRequired: true, constitutionalCarry: false, description: "Michigan requires a Concealed Pistol License (CPL) for concealed carry. The state enacted new gun safety laws in 2023 including universal background checks, secure storage requirements, and a red flag law." },
];

export const getStateBySlug = (slug: string): State | undefined =>
  states.find((s) => s.slug === slug);
